CREATE TABLE [PRODUTOS](
    [CODIGO] INTEGER PRIMARY KEY NOT NULL UNIQUE, 
    [DESCRICAO] VARCHAR(200) NOT NULL, 
    [DATA_CADASTRO] DATE NOT NULL, 
    [ESTOQUE_MINIMO] DECIMAL(15, 2), 
    [ESTOQUE_MAXIMO] DECIMAL(15, 2), 
    [PRECO_CUSTO] DECIMAL(15, 2), 
    [PRECO_VENDA] DECIMAL(15, 2));
